name: input-value-log

on:
  workflow_dispatch:
    inputs:
      value1:
        required: true
        type: number
      value2:
        required: true
        type: string
      value3:
        required: true
        type: boolean

permissions:
  contents: write

jobs:
  input-value-log:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: "Asia/Tokyo"

    steps:
      - uses: actions/checkout@v4

      - name: input Value Log
        run: |
          echo '::notice title=タイトル::テスト'
