name: input-value-log

on:
  workflow_dispatch:
    inputs:
      deploy:
        type: choice
        description: Deploy target
        options:
          - yes
          - no
      environment:
        type: choice
        description: Deploy target
        options:
          - dev1
          - dev2
          - prod

permissions:
  contents: write

jobs:
  input-value-log:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: "Asia/Tokyo"

    steps:
      - uses: actions/checkout@v4

      - name: input Value Log
        run: |
          echo '::notice title=タイトル::テスト'
