name: tag_deploy

on:
  workflow_dispatch:

jobs:
  add_tag:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # 前回のリリースタグを取得する
      - name: test
        run: |
          echo "test"
          echo ${{ github.ref }}
          echo ${{ github.sha }}          
